# Generated by Django 3.2.8 on 2021-10-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('votes', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('filepath', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=0)),
            ],
        ),
    ]
